version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../src:/app/src
      - ../requirements:/app/requirements
    ports:
      - 8000:8000
